### ISSUE TITLE
Cannot open file with relative path

### ISSUE THREAD

**Issue by ft-jasong** [ft-jasong/kmu_capstone#5]
```python
Traceback (most recent call last):
  File "/Users/jasong/school/kmu_capstone/src/main.py", line 60, in <module>
    tile = Tile("../asset/map/map_camp_tile2.png")
  File "/Users/jasong/school/kmu_capstone/src/main.py", line 47, in __init__
    self.ss = Spritesheet(tile_path)
  File "/Users/jasong/school/kmu_capstone/src/main.py", line 6, in __init__
    self.sheet = pygame.image.load(filename).convert()
FileNotFoundError: No file '../asset/map/map_camp_tile2.png' found in working directory '/Users/jasong/school/kmu_capstone'.
```

###
상대경로로 image load시 작동되지 않음.

**Comment by ft-jasong** [comment]
<https://stackoverflow.com/questions/2753254/how-to-open-a-file-in-the-parent-directory-in-python-in-appengine>
